export enum StorageKeys {
    Releases = 'releases',
    WatchList = 'watchList',
    HeaderFilter = 'headerFilter',
    ShowPaths = 'showPaths',
    DownloadedShows = 'downloadedShows',
    AnalyticsEnabled = 'analyticsEnabled',
    UseInbuiltTorrentClient = 'useInbuiltTorrentClient',
    ReleaseShowCacheLength = 'releaseShowCacheLength',
    UseAutoGeneratedFolderNames = 'useAutoGeneratedFolderNames',
    AutoGeneratedFolderName = 'autoGeneratedFolderName',
    WatchedEpisodes = 'watchedEpisodes',
}
