export enum StorageKeys {
    WatchList = 'watchList',
    ShowPaths = 'showPaths',
    DownloadedShows = 'downloadedShows',
    AnalyticsEnabled = 'analyticsEnabled',
    UseInbuiltTorrentClient = 'useInbuiltTorrentClient',
    ReleaseShowCacheLength = 'releaseShowCacheLength',
    UseAutoGeneratedFolderNames = 'useAutoGeneratedFolderNames',
    AutoGeneratedFolderName = 'autoGeneratedFolderName',
}
