name: Android Build ## name of the workflow

on: [push]

jobs:
    android-build:
        name: Android Build
        runs-on: ubuntu-latest # using ubuntu latest version / or you can use a specific version

        steps:
            - name: Check out Git repository # clone the repo to local ci workspace
              uses: actions/checkout@v2

            - name: Setup Java JDK
              uses: actions/setup-java@v3.3.0
              with:
                distribution: 'temurin'
                # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
                java-version: 11

            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'

            - name: Install react native application dependencies
              run: npm ci

            - name: Install node-js application dependencies
              run: cd nodejs-assets/nodejs-project && npm ci && cd ../../

            ## configure cash for gradle : will help to reduce build time
            - name: Cache Gradle Wrapper
              uses: actions/cache@v2
              with:
                  path: ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

            - name: Cache Gradle Dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-caches-
            - name: Make Gradlew Executable
              run: cd android && chmod +x ./gradlew

            - name: Generate App APK
              run: |
                  cd android && ./gradlew assembleRelease --no-daemon

            ## sign generated apk
            #      - name: Sign APK
            #        id: sign_app
            #        uses: r0adkll/sign-android-release@v1
            #        with:
            #          releaseDirectory: android/app/build/outputs/apk/release
            #          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
            #          alias: ${{ secrets.ANDROID_ALIAS }}
            #          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
            #          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v3.0.0
              with:
                  # Artifact name
                  name: Android App
                  # A file, directory or wildcard pattern that describes what to upload
                  path: android/app/build/outputs/apk/release/app-release.apk
                  # The desired behavior if no files are found using the provided path.
